### ISSUE TITLE
License approval from Penn Innovation Center

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#10]
Work with UPenn's Office of General Council on approving a BSD license for simpl open source

**Comment by sarahetoms** [comment]
@frankwiles @jefftriplett :: Do either of you have a better version of the BSD license that I can take to OGC? In this one, I don't think we do care if our copyright is retained in the source code ... or should I care? https://opensource.org/licenses/BSD-3-Clause

**Comment by frankwiles** [comment]
So you may not care about if copyright is retained in the source, but it serves the purpose of making it viral and any alteration to these licenses (other than including the name and year) makes them no longer OSI compliant ([the full list](https://opensource.org/licenses)) which means they're in total legal limbo and have no legal precedent.

**Comment by jefftriplett** [comment]
@sarahetoms keep in mind you'll want one license for the simpl.world website and another for the Simpl code. 

BSD is kind of standard in the Python world. I know a lot of people who like the Apache License too. I'm honestly not up to date on why one is better than the other. This guide is nice though for a mile high overview: https://choosealicense.com/licenses/

I would consider going with one of the creative commons licenses for the website content if that's appropriate: https://creativecommons.org/

**Comment by sarahetoms** [comment]
Spoke to David Siedell yesterday, who is bringing these license options to Penn OGC for review today. Should hear back in the next week or so

**Comment by sarahetoms** [comment]
Application in process. This actually needs approval from Penn Innovation. It has cleared OGC.

**Comment by sarahetoms** [comment]
I have received approval from Penn OGC to open source simpl
![image](https://user-images.githubusercontent.com/29779630/44858407-ecc43980-ac3f-11e8-929e-55643870b978.png)

I will open a new ticket to add this language into the source code.

**Comment by joelee484** [comment]
Awesome!  Closing this ticket out, thanks for doing the legwork here @sarahetoms
