### ISSUE TITLE
Vagrant for Simpl local dev

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#14]
I know @janeeisenstein is working on this. 

This is another asset which needs to be rolled into the Dev Community side of the website & tutorials for getting started

**Comment by joelee484** [comment]
@frankwiles @janeeisenstein -- Do we still want to suggest Vagrant for this?  Or is this deprecated now that we're thinking about Docker images and all of us develop outside of Vagrant?

**Comment by janeeisenstein** [comment]
We can definitely de-emphasize Vagrant in our docs. It would only needed if someone can't run PostgreSql locally until we have the simpl-games-api docker container.

**Comment by jefftriplett** [comment]
I'm 👍 docker/docker-compose since that's a shorter hoop to jump through.

**Comment by frankwiles** [comment]
Yeah I think we should focus entirely on Docker/docker-compose and skip Vagrant

**Comment by jefftriplett** [comment]
OK, marking this as closed closed.
