### ISSUE TITLE
Create blog on Jekyll

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#15]
I don't think the blog needs to be up before we open source, but can come immediately afterwards

**Comment by frankwiles** [comment]
This is ready to approval:

https://simpl.world/blog/

https://simpl.world/blog/welcome-to-jekyll/

**Comment by jefftriplett** [comment]
The styles are done but the fields aren't exposed in the blog template. Probably 15 minutes left to finish it.

**Comment by frankwiles** [comment]
Ah I'll finish it then

**Comment by sarahetoms** [comment]
@chadwhitman - the image overlaps with the blog title on the main screen
![image](https://user-images.githubusercontent.com/29779630/29985895-04015c42-8f2f-11e7-99e9-8f8068cccf44.png)

@jefftriplett - how do we change the main image (instead of a waterfall)?

**Comment by jefftriplett** [comment]
@sarahetoms I added some info earlier in #40. Basically each post may override the default (waterfall) by specifying a `background_photo` to use. Since the page header could be changed too, we might want to do the same thing and call it `header_photo` for more flexibility.

**Comment by jefftriplett** [comment]
LGTM
