### ISSUE TITLE
Create single player Simpl game tutorial

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#17]
1. Single game and make repo public in simplworld
2. Write step by step instructions using #16 
3. Assistance from @jefftriplett @chadwhitman to integrate into the Tutorials section of the website
4. Someone else to test the tutorial (maybe someone from Revsys like Flavio?)

**Comment by janeeisenstein** [comment]
Beginning are in the simpl-docs 'simpl-calc' branch.

**Comment by sarahetoms** [comment]
Update for asynch.io

**Comment by joelee484** [comment]
This has been done in Jane, the tutorial is within simpl-docs and will be ported to Jekyll, covered under ticket #4
