### ISSUE TITLE
Create multi player Simpl game tutorial

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#18]
1. Multi player game and make repo public in simplworld
2. Write step by step instructions using #16 
3. Assistance from @jefftriplett @chadwhitman to integrate into the Tutorials section of the website
4. Someone else to test the tutorial (maybe someone from Revsys like Flavio?)

**Comment by sarahetoms** [comment]
Will work on once asynch.io added to repos

**Comment by joelee484** [comment]
Is this good to go?  I see this tutorial in the docs, but unsure if its all done or not.

**Comment by janeeisenstein** [comment]
The tutorial is complete and ready to test.

**Comment by joelee484** [comment]
I've been running through this, I have the simpl-games-api and the model-service running (yay!).  However, when I get to the frontend portion, I can't login with the test user (followed all instructions, default env was setup successfully).

**Comment by joelee484** [comment]
This is the portion that is not working:
`In Chrome, head to http://localhost:8000/ and login as s1@div.edu with password s1`

**Comment by janeeisenstein** [comment]
@joelee484 Please try following the getting started instructions for running simpl-calc-ui. I'm wondering whether it's Windows or the tutorial that is failing you.

**Comment by janeeisenstein** [comment]
@joelee484 Please try following the getting started instructions for running simpl-calc-ui. I'm wondering whether it's Windows or the tutorial that is failing you.

**Comment by joelee484** [comment]
Tutorial has been tested and working!  Made some edits to the docs, but we're good to go to close this out
