### ISSUE TITLE
Retire / Archive old Simpl repos

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#19]
@frankwiles Need information on what this process will entail.

**Comment by joelee484** [comment]
Is this still relevant @frankwiles ?

**Comment by frankwiles** [comment]
Yeah need to kill the repos on gitlab.com and githost for example to avoid our own internal confusion!

**Comment by frankwiles** [comment]
I've removed all of the gitlab.com repos, but have left the githost ones temporarily in case we discover we need something or need to refer to something.

**Comment by joelee484** [comment]
Is this good to close @frankwiles ?

**Comment by frankwiles** [comment]
Yep!
