### ISSUE TITLE
Convert current Simpl docs to Jekyll

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#4]
Move over from githost. 

@janeeisenstein - I wasn't clear if we have documentation cleanup tasks to do as well. My recommendation, is let's get them converted first, archive the old, and we can work on cleaning up the docs in github.

**Comment by janeeisenstein** [comment]
The most recent updates of simpl-docs are on the 'simpl-calc' branch.

**Comment by fcurella** [comment]
reminder: to get syntax highlight for JSX, make sure to configure jekyll to use `pygments` (https://jekyllrb.com/docs/templates/#code-snippet-highlighting) and install `jsx-lexer` (https://pypi.python.org/pypi/jsx-lexer/0.0.4)

**Comment by jefftriplett** [comment]
@fcurella `jsx-lexer` isn't on the Github's approved / whitelisted list of plugins when I looked last week. Here's their list: https://pages.github.com/versions/ 

However, I found a client side JS version when I looked last week which we should be able to drop in.

**Comment by jefftriplett** [comment]
I'm not sure which is the better to use but Google tells me we have several options. `highlight.js` was just the first on the list: https://highlightjs.org/

**Comment by fcurella** [comment]
@jefftriplett jsx-lexel is not a jekyll plugin. It's a plugin for `pygments`

**Comment by sarahetoms** [comment]
Needs to be updated with latest version asynch.io

**Comment by joelee484** [comment]
Moving this to backlog for now and clearing assignee, will cover in meeting later this month.

**Comment by jefftriplett** [comment]
cc @joelee484 Done in #70 and #73

**Comment by janeeisenstein** [comment]
@jefftriplett There are some rough patches in the converted docs. I will them as I review the content.
