### ISSUE TITLE
Blog template / layout cleanup

### ISSUE THREAD

**Issue by jefftriplett** [simplworld/simpl.world.website#40]
Here are a few things we noticed when finishing out the blog:

- [x] Posts support `author_photo` which defaults to an Ewok. We probably need read photos.
- [ ] When blog post titles are wide, they are behind the author_photo.
- [ ] Posts support `background_photo` which is their thumbnail image. We may one a small image and a large image if you want this to also be the blog header background image. These default to the `blog_one.png` / waterfall photo.
- [x] ~Homepage shows the latest two featured posts, but the image is just a default of a tower.~ This requirement was changed from our original concept. I am happy to revisit, but we actually removed the blog posts from the homepage in a previous revision.

**Comment by joelee484** [comment]
@chadwhitman -- We've circled back to the Open Source efforts in simpl last week, looks like these issues are still pending, do you think you'll have time to circle back around to this at some point?  Not a priority vs. your other work, but wanted to put this back on your radar :)

**Comment by jefftriplett** [comment]
cc @joelee484 and @janeeisenstein can you both please share photos with me and I'll get you added?

**Comment by joelee484** [comment]
Yep no problem, see attached.  
![joelee](https://user-images.githubusercontent.com/4029438/43283244-5fb8ad1a-90e6-11e8-85b0-6fbca4bf6bd5.PNG)

**Comment by jefftriplett** [comment]
@joelee484 I spy Joe!!! ![](https://www.evernote.com/shard/s27/sh/fc4e241f-75d5-49f9-b1b5-c63792250c60/1c216dd928edb219/res/c9ef7353-4724-4b12-b2d0-6dd3374b781b/skitch.png)

**Comment by jefftriplett** [comment]
@joelee484 ok, you are merged into the website/eternity.

**Comment by jefftriplett** [comment]
@joelee484 everything else on this ticket I can help @chadwhitman with, but it involves moving some SASS/CSS/HTML design assets/techniques around. I'm happy to have this conversation when his schedule allows for it. I'm moving to waiting for acceptance for now.

I can also update the other photos too as y'all send them to me.
