### ISSUE TITLE
Evaluate packaging, NPM and PyPi for simpl apps

### ISSUE THREAD

**Issue by joelee484** [simplworld/simpl.world.website#58]
Assess what makes sense to live in NPM/PyPi, sign up for an account if needed and prepare/upload packages (and adjust requirements/docs to reflect this).

**Comment by janeeisenstein** [comment]
Python installables go to PyPi. Javascript installables (simpl-react) go to NPM. I set up lldev accounts for both whose credentials are in LastPass.

**Comment by janeeisenstein** [comment]
Completed test uploads of simpl-client, simpl-authenticator, and simpl-usersto https://test.pypi.org/. 

Once the simpl-client and simpl-authenticator packages are available on pypi.org, we can get rid of simpl-modelservice's dependency_links and upload simpl-modelservice to pypi.

**Comment by janeeisenstein** [comment]
Being able to download from pypi and npmjs is not needed to go Open Source.
