### ISSUE TITLE
Create simpl.world.website and folder structure

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#6]
The website will also be open source, allowing the community to do pull requests to make updates.
@janeeisenstein will create the repo (complete) and @jefftriplett will get the folder structure in place.

- [x] Website 
  - [x] Home
  - [x] About
  - [x] Practioner
  - [x] Developer
  - [x] other static-ish assets)
- [ ] Docs (developer)
- [ ] Dev Tutorials
- [x] Blog
- [ ] Community Help

**Comment by jefftriplett** [comment]
PR #26 lays the ground work for this. All that's really missing are the three unchecked options which I need a layout for. IMO, we address these as separate issues.
