### ISSUE TITLE
Create Simpl organization on Docker Hub

### ISSUE THREAD

**Issue by joelee484** [simplworld/simpl.world.website#64]

**Comment by joelee484** [comment]
This has been done, organization "simpldocker" has been created.  If @janeeisenstein @frankwiles you give me your Docker Hub usernames I will add them to the org (and anyone else that should be invited).

**Comment by frankwiles** [comment]
I'm 'frankwiles' on there.  You should also add 'gladiatr72' which is
Stephen in case he needs to do anything around automated builds.

--
Frank Wiles
President/Founder of REVSYS
www.revsys.com
@fwiles

**Comment by joelee484** [comment]
Done!
