### ISSUE TITLE
simpl.world hosting & DNS

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#7]
github will host the simpl.world website. We will need the DNS pointed to this.

Adding @frankwiles to assist @joelee484 with the task. Doesn't need to be in place until other tickets in this label category are completed.

**Comment by jefftriplett** [comment]
Btw, we'll want SSL on this domain. To my knowledge, our only option might be a free account on Cloudflare: https://www.cloudflare.com/

We use the free option for all of the *.djangocon.us websites and for my personal website. 

You'll also want to decide if you want `www.simpl.world` to redirect to `simpl.world` or vice versa. That can be setup vis Cloudflare's DNS too. One will always redirect to the other though. 

If you don't want to deep dive into docs, your DNS will look something like: 

![](https://www.evernote.com/shard/s27/sh/33b8246b-b08d-44e6-834e-97fa1e87fa83/26a508c5c661ad98/res/3a6c6f0e-e503-401d-bb23-67be2b3d075d/skitch.png)

**Comment by sarahetoms** [comment]
@jefftriplett :: Can you provide the A records and we'll get DNS pointed. Thanks

**Comment by frankwiles** [comment]
Just an FYI it'll likely be a CNAME record, not an A record.

**Comment by sarahetoms** [comment]
Folks - could I please get the CNAME record? Can't get the website up without something! :)

**Comment by sarahetoms** [comment]
Created a cloudflare account and shared credentials with @jefftriplett

**Comment by jefftriplett** [comment]
@sarahetoms CloudFlare has been updated and I need the name servers for simpl.world updated to:

- darwin.ns.cloudflare.com
- hera.ns.cloudflare.com

**Comment by sarahetoms** [comment]
Ticket raised with ESS

https://whartoncoreservices.zendesk.com/hc/requests/44426

**Comment by sarahetoms** [comment]
DNS has been updated. Now we wait ⌛️

**Comment by jefftriplett** [comment]
It's live: http://simpl.world/ 

CloudFlare needs an hour to a day to issue our cert (you might double check email too in case you get something). Then I'll switch it to https://simpl.world/ -- They manage the non-secure http to secure https automatically for us. It's set and forget basically.
