### ISSUE TITLE
simpl.world website design

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#8]

**Comment by jefftriplett** [comment]
I'm happy to work you through this. The gist is:

- `_layouts/base.html` is where your main html will go
- `assets/css` for CSS. You can even use scss and it'll compile it
- `assets/*` where * is images (or img), js, etc.

**Comment by chadwhitman** [comment]
great thanks @jefftriplett, I'll drop you a line if a run into any issues!
