### ISSUE TITLE
Sanitize & Ready Simpl repos for being open to public

### ISSUE THREAD

**Issue by sarahetoms** [simplworld/simpl.world.website#9]
1. Remove API keys
2. Export/Import to remove version tags (we want the initial version to be 0.7)
3. Remove Wharton specific references (Canvas, django_courses, etc)
4. Move to Django 1.11.x (which should be quick) 

I've asked @frankwiles for full list of actions

> Under the category of “Sanitizing the SIMPL repos” - what is the full set of actions that you’d recommend. I have removing API keys. Anything else that’s either hardcoded or a security risk that needs to be removed, refactored?

**Comment by janeeisenstein** [comment]
All repos were migrated to Django 1.11 earlier this year.
