### ISSUE TITLE
Activate Forum link

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl.world.website#92]
Currently, clicking on the 'FORUM' header link takes me to https://www.discourse.org. It should take me to a Simpl Forum -- right?

**Comment by janeeisenstein** [comment]
@joelee484 It appears this ticket depends on #11 and #12

**Comment by janeeisenstein** [comment]
@joelee484 If we can't get this set up before the public announcement, should the link be deactivated?

**Comment by joelee484** [comment]
I'll do this next week!

**Comment by joelee484** [comment]
Reached out to Discourse regarding getting this setup, there is no free tier so inquired about EDU pricing.

**Comment by joelee484** [comment]
Removed the link to the forum for now until I get this setup, I have messages out to Discourse to get this setup.

**Comment by joelee484** [comment]
Made contact with Discourse and negotiated the EDU rate for the site, setup forum.simpl.world, waiting on Ka-Wing to make the CNAME addition to the domain before I activate this.

**Comment by joelee484** [comment]
This has been done!
